freespace:
  value: <span class="freespace">Free Space</span>

values:
  - Ping
  - Post
  - Dynamic
  - Hard Code
  - Cron Job
  - ...not dying to
  - IVR
  - SEO
  - Gut
  - ...Spend a ton of time
  - API
  - User's Experience
  - Logic
  - Monetize
  - Big Opportunity
  - How much effort?
  - Algorithm
  - Can't we just...
  - Synergies
  - Sales Team
  - Ummmm...
  - Can't we just...1
  - Synergies2
  - Sales Team3
  - Ummmm...4