freespace:
  value: <span class="freespace">Free Space</span>

values:
  - Ping
  - Post
  - Dynamic
  - Hard Code
  - Cron Job
  - ...not dying to
  - IVR
  - SEO
  - Gut
  - ...Spend a ton of time
  - API
  - User's Experience
  - Logic
  - Monetize
  - Big Opportunity
  - How much effort?
  - Algorithm
  - Can't we just...
  - Synergies
  - Sales Team
  - Ummmm... OK
  - Next Actions/Steps
  - Strategy
  - New Initatives
  - Usefulness
  - I don't think that's the case